name: sd_jwt
description: Dart implementation of credential format SD-JWT and JWT/JWS in general.
version: 1.0.0
repository: https://github.com/b2cm/sd_jwt

environment:
  sdk: ^3.3.1

dependencies:
  pointycastle: ^4.0.0
  ed25519_edwards: ^0.3.1
  uuid: ^4.5.0
  json_path: ^0.7.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
