name: sd_jwt
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  #crypto_keys: ^0.3.0
  #web3dart: ^2.7.3
  pointycastle: ^3.9.1
  ed25519_edwards: ^0.3.1
  uuid: ^4.5.0
  json_path: ^0.7.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  jose: ^0.3.4
